- label: All your data in one place.<br>Get to work, instantly.
  content: Browse all your data, no matter where it lives.
  image: /img/screen-2.png
- label: Curate your data and share with your team. Build together.
  content: Preview your data from an intuitive interface.
  image: /img/screen-2.png
- label: Analyze your data with any tool. Because Dremio is for everybody.
  content: Browse all your data, no matter where it lives.
  image: /img/screen-2.png